sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rupeshpanwar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rupeshpanwar/docker-react npm run test -- --coverage