sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rupeshpanwar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rupeshpanwar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerreact"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-075890588897"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY